# Welcome to Manwe's Engineering Portfolio

theme: jekyll-theme-minimal
title: Manwe's Engineering Portfolio
description: A collection of my undergraduate engineering projects and research.

# Enable collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default settings for files
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
